const ProductList = [
  // > WEDDING BANDS     // > ENGAGEMENT RINGS    // > EARRINGS    // › BRACELETS    // › NECKLACES    // > WATCHES    // › VINTAGE RINGS    // > VINTAGE JEWELLERY
  // > PENDANTS     // > MARCASITE    // › LOOSE DIAMONDS    // > DESIGNERS
  {
    _id: "1",
    title: "Diamond Ring",
    category: "WEDDING BANDS",
    price: 960000,
    img: "../assets/products/jeweleryProduct_01.png",
  },
  {
    _id: "2",
    title: "Diamond Ring",
    category: "WEDDING BANDS",
    price: 2000,
    img: "../assets/products/jeweleryProduct_02.png",
  },
  {
    _id: "3",
    title: "Diamond neckless",
    category: "WEDDING BANDS",
    price: 100,
    img: "../assets/products/jeweleryProduct_03.png",
  },
  {
    _id: "4",
    title: "Diamond Ring",
    category: "WEDDING BANDS",
    price: 400,
    img: "../assets/products/jeweleryProduct_04.png",
  },
  {
    _id: "5",
    title: "Diamond Ring",
    category: "WEDDING BANDS",
    price: 9400,
    img: "../assets/products/jeweleryProduct_05.png",
  },
  {
    _id: "6",
    title: "Diamond Ring",
    category: "WEDDING BANDS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_06.png",
  },
  {
    _id: "7",
    title: "Diamond Ring",
    category: "WEDDING BANDS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_07.png",
  },
  {
    _id: "8",
    title: "Diamond Ring",
    category: "ENGAGEMENT RINGS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_08.png",
  },
  {
    _id: "9",
    title: "Diamond Ring",
    category: "ENGAGEMENT RINGS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_09.png",
  },
  {
    _id: "10",
    title: "Diamond Ring",
    category: "ENGAGEMENT RINGS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_10.png",
  },
  {
    _id: "11",
    title: "Diamond Ring",
    category: "ENGAGEMENT RINGS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_11.png",
  },
  {
    _id: "12",
    title: "Diamond Ring",
    category: "ENGAGEMENT RINGS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_12.png",
  },
  {
    _id: "13",
    title: "Diamond Ring",
    category: "VINTAGE RINGS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_13.png",
  },
  {
    _id: "14",
    title: "Diamond Ring",
    category: "VINTAGE RINGS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_13.png",
  },
  {
    _id: "15",
    title: "Diamond Ring",
    category: "VINTAGE RINGS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_14.png",
  },
  {
    _id: "16",
    title: "Diamond Ring",
    category: "VINTAGE RINGS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_15.png",
  },
  {
    _id: "17",
    title: "Diamond Ring",
    category: "BRACELETS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_16.png",
  },
  {
    _id: "18",
    title: "Diamond Ring",
    category: "BRACELETS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_17.png",
  },
  {
    _id: "19",
    title: "Diamond Ring",
    category: "BRACELETS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_18.png",
  },
  {
    _id: "20",
    title: "Diamond Ring",
    category: "BRACELETS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_19.png",
  },

  {
    _id: "21",
    title: "Diamond Ring",
    category: "BRACELETS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_20.png",
  },
  {
    _id: "22",
    title: "Diamond Ring",
    category: "BRACELETS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_01.png",
  },
  {
    _id: "23",
    title: "Diamond Ring",
    category: "BRACELETS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_02.png",
  },

  {
    _id: "24",
    title: "Diamond Ring",
    category: "BRACELETS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_03.png",
  },

  {
    _id: "25",
    title: "Diamond Ring",
    category: "NECKLACES",
    price: 90000,
    img: "../assets/products/jeweleryProduct_04.png",
  },
  {
    _id: "26",
    title: "Diamond Ring",
    category: "NECKLACES",
    price: 90000,
    img: "../assets/products/jeweleryProduct_05.png",
  },
  {
    _id: "27",
    title: "Diamond Ring",
    category: "NECKLACES",
    price: 90000,
    img: "../assets/products/jeweleryProduct_06.png",
  },
  {
    _id: "28",
    title: "Diamond Ring",
    category: "MARCASITE",
    price: 90000,
    img: "../assets/products/jeweleryProduct_07.png",
  },
  {
    _id: "29",
    title: "Diamond Ring",
    category: "LOOSE DIAMONDS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_08.png",
  },
  {
    _id: "30",
    title: "Diamond Ring",
    category: "LOOSE DIAMONDS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_09.png",
  },
  {
    _id: "31",
    title: "Diamond Ring",
    category: "WEDDING BANDS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_10.png",
  },
  {
    _id: "32",
    title: "Diamond Ring",
    category: "WATCHES",
    price: 90000,
    img: "../assets/products/jeweleryProduct_11.png",
  },
  {
    _id: "33",
    title: "Diamond Ring",
    category: "WATCHES",
    price: 90000,
    img: "../assets/products/jeweleryProduct_12.png",
  },
  {
    _id: "34",
    title: "Diamond Ring",
    category: "WATCHES",
    price: 90000,
    img: "../assets/products/jeweleryProduct_13.png",
  },
  {
    _id: "35",
    title: "Diamond Ring",
    category: "WATCHES",
    price: 90000,
    img: "../assets/products/jeweleryProduct_14.png",
  },
  {
    _id: "36",
    title: "Diamond Ring",
    category: "ENGAGEMENT RINGS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_15.png",
  },
  {
    _id: "37",
    title: "Diamond Ring",
    category: "EARRINGS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_16.png",
  },
  {
    _id: "38",
    title: "Diamond Ring",
    category: "EARRINGS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_17.png",
  },
  {
    _id: "39",
    title: "Diamond Ring",
    category: "EARRINGS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_18.png",
  },
  {
    _id: "40",
    title: "Diamond Ring",
    category: "EARRINGS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_19.png",
  },
  {
    _id: "41",
    title: "Diamond Ring",
    category: "VINTAGE JEWELLERY",
    price: 90000,
    img: "../assets/products/jeweleryProduct_19.png",
  },
  {
    _id: "42",
    title: "Diamond Ring",
    category: "VINTAGE JEWELLERY",
    price: 90000,
    img: "../assets/products/jeweleryProduct_20.png",
  },
  {
    _id: "43",
    title: "Diamond Ring",
    category: "VINTAGE JEWELLERY",
    price: 90000,
    img: "../assets/products/jeweleryProduct_01.png",
  },
  {
    _id: "44",
    title: "Diamond Ring",
    category: "VINTAGE JEWELLERY",
    price: 90000,
    img: "../assets/products/jeweleryProduct_02.png",
  },

  {
    _id: "45",
    title: "Diamond Ring",
    category: "PENDANTS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_03.png",
  },
  {
    _id: "46",
    title: "Diamond Ring",
    category: "PENDANTS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_04.png",
  },
  {
    _id: "47",
    title: "Diamond Ring",
    category: "PENDANTS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_05.png",
  },

  {
    _id: "48",
    title: "Diamond Ring",
    category: "DESIGNERS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_06.png",
  },

  {
    _id: "49",
    title: "Diamond Ring",
    category: "VINTAGE JEWELLERY",
    price: 90000,
    img: "../assets/products/jeweleryProduct_08.png",
  },
  {
    _id: "50",
    title: "Diamond Ring",
    category: "VINTAGE JEWELLERY",
    price: 90000,
    img: "../assets/products/jeweleryProduct_07.png",
  },
  {
    _id: "51",
    title: "Diamond Ring",
    category: "VINTAGE JEWELLERY",
    price: 90000,
    img: "../assets/products/jeweleryProduct_09.png",
  },
  {
    _id: "52",
    title: "Diamond Ring",
    category: "VINTAGE JEWELLERY",
    price: 90000,
    img: "../assets/products/jeweleryProduct_10.png",
  },

  {
    _id: "53",
    title: "Diamond Ring",
    category: "DESIGNERS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_11.png",
  },
  {
    _id: "54",
    title: "Diamond Ring",
    category: "DESIGNERS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_12.png",
  },
  {
    _id: "55",
    title: "Diamond Ring",
    category: "DESIGNERS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_13.png",
  },

  {
    _id: "56",
    title: "Diamond Ring",
    category: "DESIGNERS",
    price: 90000,
    img: "../assets/products/jeweleryProduct_14.png",
  },
];

export default ProductList;
